### ISSUE TITLE
Strip out `_hsmi` params

### ISSUE THREAD

**Issue by mimre25** [Psychosynthesis/Eraser#1]
The WeAreDeveloper newsletter uses URLS with `?_hsmi=<some_id>` to track clicks.

I would like to also strip those out of the urls. 

I'd be open to contribute a PR if this change is desired. :slightly_smiling_face:

**Comment by Psychosynthesis** [comment]
@mimre25 hi! Can you provide example url please?

I plan to make the list of cleared parameters configurable in the near future, so there is no particular need to add additional parameters to the code now. But I will take into account the parameter you specified in the list of those blocked by default.

**Comment by mimre25** [comment]
Here are a few examples:

https://github.blog/2024-06-11-10-years-of-the-github-security-bug-bounty-program/?_hsmi=312482955
https://press.aboutamazon.com/2024/6/aws-announces-230-million-commitment-for-generative-ai-startups?_hsmi=312482955
https://wizardzines.com/zines/oh-shit-git/?_hsmi=312482955

I think those `_hsmi` are hubspot tracking identifiers (see [here](https://community.hubspot.com/t5/Email-Marketing-Tool/Identifying-Email-content-ID-and-Internal-Hubspot-ID-hsmi-and/m-p/477160)).


> I plan to make the list of cleared parameters configurable in the near future

Looking forward to this! I was actually first checking whether this is already possible :sweat_smile:

**Comment by Psychosynthesis** [comment]
@mimre25 Hi! I've added a couple of new parameters to the list, including the one you requested.

**Comment by mimre25** [comment]
@Psychosynthesis 

With the latest update the `_hsmi` ones are back in again.

They are also not on the list for firefox in https://github.com/Psychosynthesis/Eraser/blob/main/src/firefox/common/constants.js#L11.

As a general thought: would it be possible to make the parameters user-definable (eg allow userse to add their own params to the pre-configured ones)?
